In [1]:
import snscrape

In [2]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('Minyak Goreng until:2022-05-15 since:2020-01-01').get_items()):
    if i>1000000:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.user.location])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'location'])

In [3]:
tweets_df2

,Datetime,Tweet Id,Text,Username,location
0,2022-05-14 23:59:15+00:00,1525626827091214336,@Dickystyawan11 @seruanhl @AgusYudhoyono Bangg...,zoelregar,
1,2022-05-14 23:58:07+00:00,1525626545720610816,@eg_nrs Saya beli minyak goreng curah di warun...,DestiMelliana,
2,2022-05-14 23:56:22+00:00,1525626102093611008,Kang dia masak nasi goreng guna minyak ron95 h...,ef_hash,
3,2022-05-14 23:53:54+00:00,1525625484037398528,@BinPekok @JerapahBZP @bachrum_achmadi @ruhuts...,bambang_Afr,
4,2022-05-14 23:50:33+00:00,1525624639589785600,"@KING_RAJA_ID Mandalika bukannya boncos y, mas...",bambang_Afr,
...,...,...,...,...,...
498269,2020-01-01 01:38:56+00:00,1212186413505990656,@Mushthofa_22 Page 1 \nTanganku kecipratan min...,bungkusan__,home sweet home
498270,2020-01-01 01:34:46+00:00,1212185364942581760,Dari taon ke taon selalu waspada tuh Cipratan ...,TR120807,tr üíù
498271,2020-01-01 00:49:10+00:00,1212173885929447424,@lliaeka Minyak goreng di dapur banyak,borapipam,konohagakure
498272,2020-01-01 00:28:06+00:00,1212168585780416512,"Minyak goreng habis, popok habis, indomie habi...",chevyrama,Indonesia
498273,2020-01-01 00:13:04+00:00,1212164802824396802,grosir minyak goreng terbaru https://t.co/xGIh...,ErniestKu,

In [4]:
tweets_df2.to_csv('hasil scraping1.csv', sep=',', index=False)

In [ ]:
print(dir(tweet.user))